### ISSUE TITLE
Error when running proxy

### ISSUE THREAD

**Issue by tolleiv** [AOEpeople/sentinel#5]
Seems that `proxy` command is broken atm. (tested in Ubuntu and MacOS)
```
python3 main.py proxy
Traceback (most recent call last):
  File "/sentinel/main.py", line 22, in <module>
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: proxy() takes 0 positional arguments but 1 was given
```

**Comment by kschu91** [comment]
fixed in [v0.2.1](https://github.com/AOEpeople/sentinel/releases/tag/v0.2.1)
